import * as XLSX from 'xlsx';
import { Student, Teacher, UserAccount, Gender, UserRole } from '../types';

export type ImportType = 'STUDENT' | 'TEACHER' | 'ACCOUNT';

export interface ParsedImportRow {
  rowNumber: number;
  raw: Record<string, any>;
  
  // Normalized profile fields
  code: string;
  fullName: string;
  email: string;
  phone: string;
  gender: Gender;
  birthDate: string;
  address: string;
  subjectsOrSpecialties: string[];
  hourlyRate?: number;
  guardianName?: string;
  guardianPhone?: string;
  guardianRelation?: string;
  status: string;
  notes?: string;

  // Account creation fields
  createAccount: boolean;
  accountRole: UserRole;
  password?: string;

  // Validation
  isValid: boolean;
  errors: string[];
  warnings: string[];
  isDuplicateInFile?: boolean;
  isDuplicateInDB?: boolean;
  codeAutoGenerated?: boolean;
}

/**
 * Normalizes a header string for flexible matching
 */
export const normalizeHeader = (str: string): string => {
  if (!str) return '';
  return str
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
};

/**
 * Flexible date parser supporting DD/MM/YYYY, YYYY-MM-DD, Excel serial numbers, Date objects
 */
export const parseFlexibleDate = (val: any): string => {
  if (!val) return '';
  if (val instanceof Date && !isNaN(val.getTime())) {
    return val.toISOString().split('T')[0];
  }
  if (typeof val === 'number') {
    // Excel date serial number check (around 1970 - 2040)
    if (val > 10000 && val < 60000) {
      try {
        const utc_days = Math.floor(val - 25569);
        const date = new Date(utc_days * 86400 * 1000);
        return date.toISOString().split('T')[0];
      } catch (e) {
        return '';
      }
    }
    return String(val);
  }

  const str = String(val).trim();
  if (!str) return '';

  // Match DD/MM/YYYY or DD-MM-YYYY
  const dmyMatch = str.match(/^(\d{1,2})[\/\-\.](\d{1,2})[\/\-\.](\d{4})$/);
  if (dmyMatch) {
    const day = dmyMatch[1].padStart(2, '0');
    const month = dmyMatch[2].padStart(2, '0');
    const year = dmyMatch[3];
    return `${year}-${month}-${day}`;
  }

  // Match YYYY/MM/DD or YYYY-MM-DD
  const ymdMatch = str.match(/^(\d{4})[\/\-\.](\d{1,2})[\/\-\.](\d{1,2})$/);
  if (ymdMatch) {
    const year = ymdMatch[1];
    const month = ymdMatch[2].padStart(2, '0');
    const day = ymdMatch[3].padStart(2, '0');
    return `${year}-${month}-${day}`;
  }

  // If only year is provided (e.g. 2015)
  if (/^\d{4}$/.test(str)) {
    return `${str}-01-01`;
  }

  return str;
};

/**
 * Parses gender string
 */
export const parseGender = (val: any): Gender => {
  if (!val) return 'Nam';
  const str = String(val).trim().toLowerCase();
  if (str.includes('nu') || str.includes('nữ') || str.includes('female') || str === 'f') {
    return 'Nữ';
  }
  if (str.includes('khac') || str.includes('khác') || str.includes('other')) {
    return 'Khác';
  }
  return 'Nam';
};

/**
 * Generates sample Excel templates
 */
export const generateTemplateExcel = (type: ImportType) => {
  let fileName = '';
  let aoa: any[][] = [];

  if (type === 'STUDENT') {
    fileName = 'Mau_Nhap_Hoc_Vien_MinhMusic.xlsx';
    aoa = [
      [
        'Mã Học Viên (*)',
        'Họ và Tên (*)',
        'Email (*)',
        'Số Điện Thoại',
        'Ngày Sinh (YYYY-MM-DD hoặc DD/MM/YYYY)',
        'Giới Tính (Nam/Nữ)',
        'Môn Học Đăng Ký (cách nhau dấu phẩy)',
        'Địa Chỉ',
        'Họ Tên Phụ Huynh',
        'SĐT Phụ Huynh',
        'Mối Quan Hệ (Mẹ/Cha/Bà/...)',
        'Trạng Thái (active/trial/reserved)',
        'Tạo Tài Khoản (Có/Không)',
        'Mật Khẩu Khởi Tạo (để trống lấy mặc định)',
        'Ghi Chú'
      ],
      [
        'HV010',
        'Nguyễn Gia Hân',
        'giahan.nguyen@gmail.com',
        '0912345678',
        '2014-06-15',
        'Nữ',
        'Piano, Thanh nhạc',
        'Phường Bến Nghé, Quận 1, TP.HCM',
        'Nguyễn Văn Hùng',
        '0909123456',
        'Cha',
        'active',
        'Có',
        'MinhMusic@2024',
        'Học viên năng khiếu Piano'
      ],
      [
        'HV011',
        'Trần Minh Đức',
        'minhduc.tran@gmail.com',
        '0988776655',
        '2012-10-22',
        'Nam',
        'Guitar Acoustic',
        'Bình Thạnh, TP.HCM',
        'Lê Thị Thu',
        '0988112233',
        'Mẹ',
        'active',
        'Có',
        'MinhMusic@2024',
        'Lớp Guitar đệm hát'
      ],
      [
        '', // Để trống mã để hệ thống tự động sinh HV012
        'Phạm Quỳnh Anh',
        'quynhanh.pham@gmail.com',
        '0977665544',
        '18/03/2015',
        'Nữ',
        'Violin',
        'Quận 3, TP.HCM',
        'Phạm Hoàng Nam',
        '0977112233',
        'Cha',
        'active',
        'Có',
        'MinhMusic@2024',
        'Đăng ký khóa Violin cơ bản'
      ]
    ];
  } else if (type === 'TEACHER') {
    fileName = 'Mau_Nhap_Giao_Vien_MinhMusic.xlsx';
    aoa = [
      [
        'Mã Giáo Viên (*)',
        'Họ và Tên (*)',
        'Email (*)',
        'Số Điện Thoại (*)',
        'Ngày Sinh (YYYY-MM-DD hoặc DD/MM/YYYY)',
        'Giới Tính (Nam/Nữ)',
        'Bộ Môn Giảng Dạy (cách nhau dấu phẩy)',
        'Thù Lao / Buổi (VNĐ)',
        'Địa Chỉ',
        'Trạng Thái (active/on_leave)',
        'Tạo Tài Khoản (Có/Không)',
        'Mật Khẩu Khởi Tạo (để trống lấy mặc định)',
        'Tiểu Sử / Giới Thiệu'
      ],
      [
        'GV008',
        'Lê Hoàng Long',
        'hoanglong.le@minhmusic.vn',
        '0903112233',
        '1992-04-10',
        'Nam',
        'Piano, Keyboard, Cảm thụ âm nhạc',
        350000,
        'Quận 10, TP.HCM',
        'active',
        'Có',
        'MinhMusic@2024',
        'Tốt nghiệp Nhạc viện TP.HCM chuyên ngành Piano Jazz'
      ],
      [
        'GV009',
        'Ngô Mỹ Duyên',
        'myduyen.ngo@minhmusic.vn',
        '0918223344',
        '25/11/1995',
        'Nữ',
        'Thanh nhạc, Hợp xướng',
        300000,
        'Quận Phú Nhuận, TP.HCM',
        'active',
        'Có',
        'MinhMusic@2024',
        'Giảng viên Thanh nhạc thính phòng & nhạc nhẹ'
      ],
      [
        '', // Tự động sinh mã GV
        'Vũ Quốc Tuấn',
        'quoctuan.vu@minhmusic.vn',
        '0933445566',
        '1990-08-19',
        'Nam',
        'Guitar, Ukulele, Bass',
        320000,
        'Quận 7, TP.HCM',
        'active',
        'Có',
        'MinhMusic@2024',
        'Nhiều năm kinh nghiệm biểu diễn ban nhạc acoustic'
      ]
    ];
  } else {
    fileName = 'Mau_Nhap_Tai_Khoan_MinhMusic.xlsx';
    aoa = [
      [
        'Họ và Tên (*)',
        'Email (*)',
        'Số Điện Thoại',
        'Vai Trò (STUDENT/TEACHER/PARENT/ADMIN)',
        'Mã Hồ Sơ Liên Kết (nếu có)',
        'Mật Khẩu Khởi Tạo',
        'Trạng Thái (active/pending/suspended)',
        'Ghi Chú'
      ],
      [
        'Nguyễn Văn Hùng',
        'hung.nguyen.parent@gmail.com',
        '0909123456',
        'PARENT',
        'PH005',
        'MinhMusic@2024',
        'active',
        'Phụ huynh học viên Nguyễn Gia Hân'
      ],
      [
        'Trần Đình Khang',
        'khang.tran@minhmusic.vn',
        '0911223344',
        'TEACHER',
        'GV010',
        'MinhMusic@2024',
        'active',
        'Tài khoản giảng viên mới'
      ]
    ];
  }

  const wb = XLSX.utils.book_new();
  const ws = XLSX.utils.aoa_to_sheet(aoa);

  // Set column widths
  ws['!cols'] = [
    { wch: 15 },
    { wch: 24 },
    { wch: 28 },
    { wch: 16 },
    { wch: 22 },
    { wch: 16 },
    { wch: 30 },
    { wch: 28 },
    { wch: 20 },
    { wch: 16 },
    { wch: 16 },
    { wch: 16 },
    { wch: 16 },
    { wch: 20 },
    { wch: 30 }
  ];

  XLSX.utils.book_append_sheet(wb, ws, 'Mau_Nhap_Lieu');
  XLSX.writeFile(wb, fileName);
};

/**
 * Generates sample CSV template with UTF-8 BOM
 */
export const generateTemplateCSV = (type: ImportType) => {
  let fileName = '';
  let content = '';

  if (type === 'STUDENT') {
    fileName = 'Mau_Nhap_Hoc_Vien_MinhMusic.csv';
    content =
      'Mã Học Viên,Họ và Tên,Email,Số Điện Thoại,Ngày Sinh,Giới Tính,Môn Học,Địa Chỉ,Họ Tên Phụ Huynh,SĐT Phụ Huynh,Mối Quan Hệ,Trạng Thái,Tạo Tài Khoản,Mật Khẩu,Ghi Chú\n' +
      'HV010,Nguyễn Gia Hân,giahan.nguyen@gmail.com,0912345678,2014-06-15,Nữ,"Piano, Thanh nhạc","Quận 1, TP.HCM",Nguyễn Văn Hùng,0909123456,Cha,active,Có,MinhMusic@2024,Năng khiếu Piano\n' +
      'HV011,Trần Minh Đức,minhduc.tran@gmail.com,0988776655,2012-10-22,Nam,"Guitar Acoustic","Bình Thạnh, TP.HCM",Lê Thị Thu,0988112233,Mẹ,active,Có,MinhMusic@2024,Guitar đệm hát\n' +
      ',Phạm Quỳnh Anh,quynhanh.pham@gmail.com,0977665544,2015-03-18,Nữ,Violin,"Quận 3, TP.HCM",Phạm Hoàng Nam,0977112233,Cha,active,Có,MinhMusic@2024,Violin cơ bản\n';
  } else if (type === 'TEACHER') {
    fileName = 'Mau_Nhap_Giao_Vien_MinhMusic.csv';
    content =
      'Mã Giáo Viên,Họ và Tên,Email,Số Điện Thoại,Ngày Sinh,Giới Tính,Bộ Môn Giảng Dạy,Thù Lao / Buổi,Địa Chỉ,Trạng Thái,Tạo Tài Khoản,Mật Khẩu,Tiểu Sử\n' +
      'GV008,Lê Hoàng Long,hoanglong.le@minhmusic.vn,0903112233,1992-04-10,Nam,"Piano, Keyboard",350000,"Quận 10, TP.HCM",active,Có,MinhMusic@2024,Tốt nghiệp Nhạc viện TP.HCM\n' +
      'GV009,Ngô Mỹ Duyên,myduyen.ngo@minhmusic.vn,0918223344,1995-11-25,Nữ,"Thanh nhạc, Hợp xướng",300000,"Quận Phú Nhuận, TP.HCM",active,Có,MinhMusic@2024,Giảng viên Thanh nhạc\n';
  } else {
    fileName = 'Mau_Nhap_Tai_Khoan_MinhMusic.csv';
    content =
      'Họ và Tên,Email,Số Điện Thoại,Vai Trò,Mã Hồ Sơ Liên Kết,Mật Khẩu,Trạng Thái,Ghi Chú\n' +
      'Nguyễn Văn Hùng,hung.nguyen.parent@gmail.com,0909123456,PARENT,PH005,MinhMusic@2024,active,Phụ huynh học viên\n' +
      'Trần Đình Khang,khang.tran@minhmusic.vn,0911223344,TEACHER,GV010,MinhMusic@2024,active,Tài khoản giảng viên mới\n';
  }

  // Prepend UTF-8 BOM so Excel opens with proper Vietnamese characters
  const bom = new Uint8Array([0xef, 0xbb, 0xbf]);
  const blob = new Blob([bom, content], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', fileName);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

/**
 * Parses an uploaded File (Excel or CSV) into structured data rows
 */
export const parseUploadedFile = async (
  file: File,
  importType: ImportType,
  existingStudents: Student[] = [],
  existingTeachers: Teacher[] = [],
  existingAccounts: UserAccount[] = []
): Promise<ParsedImportRow[]> => {
  const arrayBuffer = await file.arrayBuffer();
  const workbook = XLSX.read(arrayBuffer, { type: 'array', cellDates: true });
  const firstSheetName = workbook.SheetNames[0];
  const worksheet = workbook.Sheets[firstSheetName];

  // Convert to JSON array of objects with header row
  const rawRows: any[] = XLSX.utils.sheet_to_json(worksheet, { defval: '' });

  if (!rawRows || rawRows.length === 0) {
    return [];
  }

  // Pre-calculate sets for duplicate detection
  const existingEmails = new Set(existingAccounts.map(a => (a.email || '').toLowerCase().trim()));
  (existingStudents || []).forEach(s => { if (s.email) existingEmails.add(s.email.toLowerCase().trim()); });
  (existingTeachers || []).forEach(t => { if (t.email) existingEmails.add(t.email.toLowerCase().trim()); });

  const existingStudentCodes = new Set((existingStudents || []).map(s => (s.code || '').toUpperCase().trim()));
  const existingTeacherCodes = new Set((existingTeachers || []).map(t => (t.code || '').toUpperCase().trim()));

  const seenEmailsInFile = new Set<string>();
  const seenCodesInFile = new Set<string>();

  // Determine starting number for auto-generating codes
  let currentStudentSeq = 1;
  existingStudentCodes.forEach(c => {
    const m = c.match(/^HV(\d+)$/i);
    if (m) {
      const n = parseInt(m[1], 10);
      if (!isNaN(n) && n >= currentStudentSeq) currentStudentSeq = n + 1;
    }
  });

  let currentTeacherSeq = 1;
  existingTeacherCodes.forEach(c => {
    const m = c.match(/^GV(\d+)$/i);
    if (m) {
      const n = parseInt(m[1], 10);
      if (!isNaN(n) && n >= currentTeacherSeq) currentTeacherSeq = n + 1;
    }
  });

  const parsedList: ParsedImportRow[] = [];

  rawRows.forEach((row, index) => {
    // Flatten and match row keys using normalizeHeader
    const rowMap: Record<string, any> = {};
    Object.keys(row).forEach(k => {
      rowMap[normalizeHeader(k)] = row[k];
    });

    // Helper to find value from possible aliases
    const findVal = (aliases: string[]) => {
      for (const alias of aliases) {
        const norm = normalizeHeader(alias);
        if (rowMap[norm] !== undefined && rowMap[norm] !== '') {
          return rowMap[norm];
        }
      }
      // Partial search fallback
      for (const k of Object.keys(rowMap)) {
        for (const alias of aliases) {
          const norm = normalizeHeader(alias);
          if (k.includes(norm) && rowMap[k] !== undefined && rowMap[k] !== '') {
            return rowMap[k];
          }
        }
      }
      return '';
    };

    // Extract fields
    const rawFullName = String(findVal(['ho va ten', 'ho ten', 'ten', 'full name', 'fullname', 'name', 'ho va ten hoc vien', 'ho va ten giao vien'])).trim();
    let rawCode = String(findVal(['ma', 'ma hoc vien', 'ma giao vien', 'ma hv', 'ma gv', 'code', 'student code', 'teacher code', 'ma ho so'])).trim().toUpperCase();
    let rawEmail = String(findVal(['email', 'thu dien tu', 'mail', 'dia chi email'])).trim().toLowerCase();
    const rawPhone = String(findVal(['so dien thoai', 'sdt', 'dien thoai', 'phone', 'mobile', 'telephone'])).trim();
    const rawBirthDate = parseFlexibleDate(findVal(['ngay sinh', 'sinh nhat', 'nam sinh', 'dob', 'birthdate', 'birth date']));
    const rawGender = parseGender(findVal(['gioi tinh', 'phai', 'gender', 'sex']));
    const rawAddress = String(findVal(['dia chi', 'noi o', 'ho khau', 'address', 'location'])).trim();
    const rawSubjectsStr = String(findVal(['mon hoc', 'bo mon', 'chuyen mon', 'mon hoc dang ky', 'specialties', 'subject', 'subjects', 'mon'])).trim();
    const rawHourlyRateStr = findVal(['thu lao', 'muc thu lao', 'luong theo gio', 'hourly rate', 'rate', 'thu lao buoi']);
    const rawGuardianName = String(findVal(['ho ten phu huynh', 'phu huynh', 'ten phu huynh', 'nguoi giam ho', 'guardian name', 'parent name'])).trim();
    const rawGuardianPhone = String(findVal(['sdt phu huynh', 'dien thoai phu huynh', 'so dien thoai phu huynh', 'guardian phone', 'parent phone'])).trim();
    const rawGuardianRelation = String(findVal(['moi quan he', 'quan he', 'relation', 'guardian relation'])).trim() || (rawGuardianName ? 'Phụ huynh' : '');
    const rawStatus = String(findVal(['trang thai', 'tinh trang', 'status'])).trim().toLowerCase() || 'active';
    const rawCreateAcc = String(findVal(['tao tai khoan', 'tao tk', 'create account', 'account'])).trim().toLowerCase();
    const rawPassword = String(findVal(['mat khau', 'password', 'mat khau khoi tao', 'pass'])).trim();
    const rawNotes = String(findVal(['ghi chu', 'tieu su', 'gioi thieu', 'note', 'notes', 'bio'])).trim();
    const rawRoleStr = String(findVal(['vai tro', 'role', 'quyen'])).trim().toUpperCase();

    // Skip empty dummy rows
    if (!rawFullName && !rawEmail && !rawCode && !rawPhone) {
      return;
    }

    const errors: string[] = [];
    const warnings: string[] = [];
    let codeAutoGenerated = false;

    // Validate Full Name
    if (!rawFullName) {
      errors.push('Thiếu họ và tên');
    }

    // Auto-generate code if omitted
    if (!rawCode) {
      if (importType === 'STUDENT') {
        rawCode = `HV${String(currentStudentSeq).padStart(3, '0')}`;
        currentStudentSeq++;
        codeAutoGenerated = true;
        warnings.push(`Tự động cấp mã học viên: ${rawCode}`);
      } else if (importType === 'TEACHER') {
        rawCode = `GV${String(currentTeacherSeq).padStart(3, '0')}`;
        currentTeacherSeq++;
        codeAutoGenerated = true;
        warnings.push(`Tự động cấp mã giáo viên: ${rawCode}`);
      }
    }

    // Check code duplication
    let isDuplicateInDB = false;
    let isDuplicateInFile = false;

    if (rawCode) {
      if (seenCodesInFile.has(rawCode)) {
        isDuplicateInFile = true;
        errors.push(`Trùng mã ${rawCode} với dòng khác trong file`);
      } else {
        seenCodesInFile.add(rawCode);
      }

      if (importType === 'STUDENT' && existingStudentCodes.has(rawCode)) {
        isDuplicateInDB = true;
        warnings.push(`Mã ${rawCode} đã tồn tại trong danh sách học viên hiện có`);
      } else if (importType === 'TEACHER' && existingTeacherCodes.has(rawCode)) {
        isDuplicateInDB = true;
        warnings.push(`Mã ${rawCode} đã tồn tại trong danh sách giáo viên hiện có`);
      }
    }

    // Fallback Email if empty
    if (!rawEmail) {
      if (rawFullName && rawCode) {
        // Auto-generate a safe fallback email
        const safeSlug = normalizeHeader(rawFullName).replace(/\s+/g, '.');
        rawEmail = `${safeSlug}.${rawCode.toLowerCase()}@minhmusic.edu.vn`;
        warnings.push(`Tự động tạo email nội bộ: ${rawEmail}`);
      } else {
        errors.push('Thiếu địa chỉ email');
      }
    } else {
      // Validate email format
      const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
      if (!emailRegex.test(rawEmail)) {
        errors.push('Định dạng email không hợp lệ');
      }
    }

    // Check email duplication
    if (rawEmail) {
      if (seenEmailsInFile.has(rawEmail)) {
        isDuplicateInFile = true;
        errors.push(`Trùng email ${rawEmail} với dòng khác trong file`);
      } else {
        seenEmailsInFile.add(rawEmail);
      }

      if (existingEmails.has(rawEmail)) {
        isDuplicateInDB = true;
        warnings.push(`Email ${rawEmail} đã có tài khoản/hồ sơ trong hệ thống`);
      }
    }

    // Parse subjects/specialties array
    let subjectsOrSpecialties: string[] = [];
    if (rawSubjectsStr) {
      subjectsOrSpecialties = rawSubjectsStr
        .split(/[,;\-\/]+/)
        .map(s => s.trim())
        .filter(Boolean);
    }
    if (subjectsOrSpecialties.length === 0) {
      if (importType === 'STUDENT') subjectsOrSpecialties = ['Piano'];
      if (importType === 'TEACHER') subjectsOrSpecialties = ['Piano'];
    }

    // Parse Hourly Rate
    let hourlyRate: number | undefined = undefined;
    if (rawHourlyRateStr) {
      const num = Number(String(rawHourlyRateStr).replace(/[^0-9]/g, ''));
      if (!isNaN(num) && num > 0) hourlyRate = num;
    }

    // Create Account Flag
    let createAccount = true;
    if (rawCreateAcc.includes('khong') || rawCreateAcc.includes('không') || rawCreateAcc === 'false' || rawCreateAcc === '0' || rawCreateAcc === 'no') {
      createAccount = false;
    }

    // Determine Account Role
    let accountRole: UserRole = importType === 'STUDENT' ? 'STUDENT' : importType === 'TEACHER' ? 'TEACHER' : 'STUDENT';
    if (rawRoleStr) {
      if (rawRoleStr.includes('ADMIN') || rawRoleStr.includes('QUẢN TRỊ')) accountRole = 'ADMIN';
      else if (rawRoleStr.includes('TEACHER') || rawRoleStr.includes('GIÁO VIÊN') || rawRoleStr.includes('GV')) accountRole = 'TEACHER';
      else if (rawRoleStr.includes('PARENT') || rawRoleStr.includes('PHỤ HUYNH') || rawRoleStr.includes('PH')) accountRole = 'PARENT';
      else if (rawRoleStr.includes('GUARDIAN') || rawRoleStr.includes('GIÁM HỘ')) accountRole = 'GUARDIAN';
      else accountRole = 'STUDENT';
    }

    const isValid = errors.length === 0;

    parsedList.push({
      rowNumber: index + 2, // 1-based header is row 1
      raw: row,
      code: rawCode,
      fullName: rawFullName,
      email: rawEmail,
      phone: rawPhone,
      gender: rawGender,
      birthDate: rawBirthDate || '2015-01-01',
      address: rawAddress,
      subjectsOrSpecialties,
      hourlyRate,
      guardianName: rawGuardianName,
      guardianPhone: rawGuardianPhone,
      guardianRelation: rawGuardianRelation,
      status: rawStatus.includes('trial') || rawStatus.includes('thử') ? 'trial' : rawStatus.includes('reserve') || rawStatus.includes('bảo lưu') ? 'reserved' : rawStatus.includes('leave') ? 'on_leave' : 'active',
      notes: rawNotes,
      createAccount,
      accountRole,
      password: rawPassword || undefined,
      isValid,
      errors,
      warnings,
      isDuplicateInFile,
      isDuplicateInDB,
      codeAutoGenerated
    });
  });

  return parsedList;
};
